version: "3.8"

services:
    # image project
    smaert-menu-react-app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: sh -c "npm install && npm run dev"
        container_name: smaert-menu-react-app
        volumes:
            - ./src:/src/
        networks:
            - appnet
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8017:80"
        networks:
            - appnet
        depends_on:
            - smaert-menu-react-app

networks:
    appnet:
        driver: bridge